name: ROS2 Jazzy CI
on: [push]
jobs:
ros_sanity_check:
runs-on: ubuntu-latest
container:
image: ros:jazzy-ros-base
steps:
- name: Checkout Code
uses: actions/checkout@v4
- name: Run Sanity Test
shell: bash
run: |
python3 src/test_connection.py
